version: '3'

services:
  dockerise-postgres:
    image: postgres:14.4-alpine
    container_name: dockerise-postgres
    volumes:
      - dockerise-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dockerise_django
    ports:
      - "5432:5432"

  dockerise-django:
    build: .
    user: webinative
    command: python -u manage.py runserver 0:8000
    container_name: dockerise-django
    env_file:
      - ./dockerise-django.env
      - ./.env
    volumes:
      - .:/home/webinative/code
      - dockerise-django-vscode:/home/webinative/.vscode-server
    ports:
      - "8000:8000"
      - "3000:3000"
    restart: on-failure
    depends_on:
      - dockerise-postgres

volumes:
  dockerise-django-vscode:
  dockerise-postgres-data:
